### PR TITLE
Drop unused factor levels when prepping the sleuth object.

### LINKED ISSUE #69: error running sleuth_fit
Hi,

I am trying to run sleuth on the output of sailfish. I can successfully run the sleuth_prep() command, but I get an error when I try to run sleuth_fit(). 

The sleuth_prep() command I am running is: `so <- sleuth_prep(sfdata, design, target_mapping = t2g)` and the sleuth_fit() command is `sleuth_fit(so)`. 

The error output for the sleuth_fit() command is: `Error in solve.default(t(X) %*% X) : Lapack routine dgesv: system is exactly singular: U[2,2] = 0`.

I am attaching my Rscript and linking the R object output from the sleuth_prep() command. Could you please let me know if you have any suggestions for debugging?

sleuth_prep() output R object: https://dl.dropboxusercontent.com/u/204381225/sleuth_prep_output.RData

 sleuth script: [sleuth.txt](https://github.com/pachterlab/sleuth/files/291845/sleuth.txt)

Thank you for your help,
Mary

### PR DESCRIPTION
**Pull request by roryk**
Hi everyone,

This fixes #69, which was caused by unrepresented factor levels hanging around in the sample_to_covariates matrix.

### CODE REVIEW

**Comment by gresteban** [comment]
Hi,

Wondering why not just
` sample_to_covariates = droplevels(sample_to_covariates);`
instead of the for loop? Final objects seem to be `identical()`;

**Comment by roryk** [comment]
@gresteban -- ah, I didn't know droplevels() worked like that.  Thanks-- I swapped over to using that one liner instead.

**Comment by Drwhit** [comment]
Thank you for doing this... I just spent nearly a full day trying to figure out why sleuth_fit was failing... it was due to empty factor levels.

**Comment by pimentel** [comment]
this looks useful -- thanks!

really sorry about the massive delay on this. will merge in by the end of this week.

thanks,

harold

**Comment by roryk** [comment]
No worries, thanks Harold!

**Comment by roryk** [comment]
Merging Warren's p/r will get this in and I think all the merge conflicts are good so I'll close this in favor of his request.

**Pull request closed without merging**
