### PR TITLE
Added basic sleuth_save, sleuth_load and sleuth_deploy functionality

### PR DESCRIPTION
**Pull request by psturmfels**
I believe the current functions should work correctly. 
With that said, they are untested. I forgot how to make a function public (e.g. so that users
can call it), and so as of now users still can't see/call sleuth_deploy.

### CODE REVIEW

**Comment by pimentel** [comment]
@psturmfels I have updated this quite a bit. Can you please try installing it and deploying a shiny application? Once that is done, I will merge it.

**Comment by psturmfels** [comment]
The deploying seems fine, but something breaks with the shiny application and nothing I do seems to fix it.

**Comment by psturmfels** [comment]
It has something to do with the transcript view (the boxplots)

**Comment by pimentel** [comment]
did you pass the correct parameters in `sleuth_prep` to ensure that you are computing the summary statistics?

**Comment by psturmfels** [comment]
Yes. See http://lair.berkeley.edu/ellahi/ and try putting a transcript in.

**Comment by pimentel** [comment]
I don't know what to tell you, man. ¯\_(ツ)_/¯ You have to fix it. Try running it locally to figure out if this is a plotting issue or a shiny issue. Then fix it accordingly. Keep me posted. Thanks.

**Comment by psturmfels** [comment]
Hey Harold, the bug is fixed. 
I'm a surprised and frusturated that we didn't catch this error earlier as it was introduced over two months ago (b0ab4064a849e4bba0bcb1d521e5eb1f64454fec).
Everything is now in order.

**Comment by pimentel** [comment]
@psturmfels thanks for finding the issue. I removed `target_id` from this object as we had discussed some time ago and created in accessor function for bootstrap summaries. I also cleaned up some of the interfaces and documentation. the main thing is to reduce the munging inside of the plotting functions. merging now

**Pull request merged**
