### PR TITLE
Updated documentation

### PR DESCRIPTION
**Pull request by map222**
My lab is interested in the table output from sleuth to identify genes of interest. I worked on the documentation for sleuth_results, sleuth_to_matrix, and sleuth_gene_table. I added more information on the columns of the data frames that are output, based on descriptions from the google groups.

I also added example code that shows how to figure out conditions using models(), and examples of how to inspect initial results.

If this looks good, I can try to go through the other popular functions, and update the documentation.

Also, sleuth_gene_table uses the lrt test by default, while most of the rest of the functions use wt, which is somewhat confusing.

### CODE REVIEW

**Comment by pimentel** [comment]
I just realized this a few days ago -- totally and oversight/artifact of development and testing (the comment about sleuth_gene_table). Thanks for pointing this out.

Anyway, this looks fantastic! I will take a very careful look later tonight and merge it. Thanks so much!

**Comment by map222** [comment]
Another quick question. In sleuth_gene_table, is num_transcripts summed over all transcripts and all samples for a given gene? Some of the transcript numbers I saw were quite low (<10), which was surprising to me, but may be standard for RNA-seq.

**Comment by pimentel** [comment]
@map222 sorry for the delay on the merge. will hopefully actually happened today.

anyway, you are correct. it is the total number of transcripts that have the same gene name. This certainly depends on your annotation. The mean number of transcripts purging is much lower for the RefSeq annotation compared to the Ensembl annotation.

**Comment by pimentel** [comment]
Sorry for the delay. Looking it over right now.

**Comment by pimentel** [comment]
Thanks a bunch for this, @map222 ! Good stuff!

**Comment by map222** [comment]
Thanks! Writing the documentation helped me better understand what was actually going on.

**Pull request merged**
